name: nextrep
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  fpdart: ^1.1.1
  gif: ^2.3.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^3.3.1
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.3.3
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/core/
    - assets/welcome_screen/
    - assets/sign_in/
    - assets/lottie/genders/
    - assets/experience/
    - assets/exercise_images/
    - assets/data/
    - assets/workouts/

# Test comment