// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzTburaxnosRtk-49k2D05KNDXVV_I4hI',
    appId: '1:808078870152:web:1c8db76a5210f5b3a1c13d',
    messagingSenderId: '808078870152',
    projectId: 'nextrep-15900',
    authDomain: 'nextrep-15900.firebaseapp.com',
    storageBucket: 'nextrep-15900.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP-HzXNO1xP9aH9QifYwX0KQNx4Gb7uR4',
    appId: '1:808078870152:android:2fc5d060586348f9a1c13d',
    messagingSenderId: '808078870152',
    projectId: 'nextrep-15900',
    storageBucket: 'nextrep-15900.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDMmOmi31DPL8DsxCDQWpFAwagCih00z4',
    appId: '1:808078870152:ios:9709980bea6a1576a1c13d',
    messagingSenderId: '808078870152',
    projectId: 'nextrep-15900',
    storageBucket: 'nextrep-15900.firebasestorage.app',
    iosClientId: '808078870152-j8ussprgeq970lptiris7dj0setv7i6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.nextrep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDMmOmi31DPL8DsxCDQWpFAwagCih00z4',
    appId: '1:808078870152:ios:9709980bea6a1576a1c13d',
    messagingSenderId: '808078870152',
    projectId: 'nextrep-15900',
    storageBucket: 'nextrep-15900.firebasestorage.app',
    iosClientId: '808078870152-j8ussprgeq970lptiris7dj0setv7i6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.nextrep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzTburaxnosRtk-49k2D05KNDXVV_I4hI',
    appId: '1:808078870152:web:07c6fe3da15cbd07a1c13d',
    messagingSenderId: '808078870152',
    projectId: 'nextrep-15900',
    authDomain: 'nextrep-15900.firebaseapp.com',
    storageBucket: 'nextrep-15900.firebasestorage.app',
  );
}
